name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: cargo build --release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: json-patcher
        path: target/release/json-patcher
        
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: cargo build --release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: json-patcher
        path: target/release/json-patcher.exe
